// <auto-generated />
namespace asp_mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201903281355364_addingModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
